import math
import statistics
import warnings

import numpy as np
from hmmlearn.hmm import GaussianHMM
from sklearn.model_selection import KFold
from asl_utils import combine_sequences


class ModelSelector(object):
    '''
    base class for model selection (strategy design pattern)
    '''

    def __init__(self, all_word_sequences: dict, all_word_Xlengths: dict, this_word: str,
                 n_constant=3,
                 min_n_components=2, max_n_components=10,
                 random_state=14, verbose=False):
        self.words = all_word_sequences
        self.hwords = all_word_Xlengths
        self.sequences = all_word_sequences[this_word]
        self.X, self.lengths = all_word_Xlengths[this_word]
        self.this_word = this_word
        self.n_constant = n_constant
        self.min_n_components = min_n_components
        self.max_n_components = max_n_components
        self.random_state = random_state
        self.verbose = verbose

    def select(self):
        raise NotImplementedError

    def base_model(self, num_states):
        # with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=DeprecationWarning)
        # warnings.filterwarnings("ignore", category=RuntimeWarning)
        try:
            hmm_model = GaussianHMM(n_components=num_states, covariance_type="diag", n_iter=1000,
                                    random_state=self.random_state, verbose=False).fit(self.X, self.lengths)
            if self.verbose:
                print("model created for {} with {} states".format(self.this_word, num_states))
            return hmm_model
        except:
            if self.verbose:
                print("failure on {} with {} states".format(self.this_word, num_states))
            return None


class SelectorConstant(ModelSelector):
    """ select the model with value self.n_constant

    """

    def select(self):
        """ select based on n_constant value

        :return: GaussianHMM object
        """
        best_num_components = self.n_constant
        return self.base_model(best_num_components)


class SelectorBIC(ModelSelector): # tested yet # of parameters an issue 
    """ select the model with the lowest Bayesian Information Criterion(BIC) score

    http://www2.imm.dtu.dk/courses/02433/doc/ch6_slides.pdf
    Bayesian information criteria: BIC = -2 * logL + p * logN
    """

    def select(self):
        """ select the best model for self.this_word based on
        BIC score for n between self.min_n_components and self.max_n_components

        :return: GaussianHMM object
        """
        warnings.filterwarnings("ignore", category=DeprecationWarning)

        #  BIC = -2 * logL + p * logN  where L is the likelihood p is amount of parameters and N is amount of data points
        best_num_components = self.min_n_components
        lowest_bic_score = float("inf")
        for num_components in range(self.min_n_components, self.max_n_components+1):
            features = len( self.X[1] )
            data_points = len( self.lengths )  
            model = self.base_model(num_components)
            try:
                logL = model.score(self.X, self.lengths)
            except:
                logL = float("-inf")
                pass
            bic = -2*logL + np.log( data_points )*(num_components*num_components)+(2*num_components*features-1)
            if np.any(bic < lowest_bic_score):
                best_num_components = num_components
                lowest_bic_score = bic
        return self.base_model(best_num_components)


class SelectorDIC(ModelSelector): #tested
    ''' select best model based on Discriminative Information Criterion

    Biem, Alain. "A model selection criterion for classification: Application to hmm topology optimization."
    Document Analysis and Recognition, 2003. Proceedings. Seventh International Conference on. IEEE, 2003.
    http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.58.6208&rep=rep1&type=pdf
    DIC = log(P(X(i)) - 1/(M-1)SUM(log(P(X(all but i))
    '''

    def select(self):
        warnings.filterwarnings("ignore", category=DeprecationWarning)
        
        best_num_components = self.min_n_components #minimum as default 
        highest_dic_score =  float("-inf")
        #compares a model to the competing class by making use of the competing class's dataset generated by models of the competing class
        for num_components in range(self.min_n_components, self.max_n_components+1):
            #plug in self.X and all other words' self.x into equation 
            #compute likelihood of word and likelihood of all other words(anti-likelihood)
            model = self.base_model(num_components)
            try:
                log_l = model.score(self.X, self.lengths)
            except:
                log_l = float("-inf")
                pass
            log_anti_l = self.createLogAntiLikelihood(model)#returns average likelihood
            alpha = 0.2 # optimal normalizer in Figure 1. Recognition rate for DIC and BIC as function of the parameter alpha.
            dic = log_l - (alpha*log_anti_l)
            if dic > highest_dic_score:
                best_num_components = num_components
                highest_dic_score = dic
        return self.base_model(best_num_components)
    def createLogAntiLikelihood(self, model):
        all_l = []
        for word, val in self.hwords.items():
            if word != self.this_word:
                X, lengths = self.hwords[word] #can be val as well
                try:
                    singular_log_l = model.score(X, lengths)
                    all_l.append( singular_log_l )
                except:
                    pass
        if len(all_l) > 0:
            average = sum(all_l)/float(len(all_l))
        elif len(all_l) == 0:
            average = float("inf") 
        return average
            

class SelectorCV(ModelSelector): #tested
    ''' select best model based on average log Likelihood of cross-validation folds
    '''

    def select(self):
        warnings.filterwarnings("ignore", category=DeprecationWarning)

        best_num_components = self.min_n_components #minimum as default 
        best_log_l = float("-inf")
        for num_components in range(self.min_n_components, self.max_n_components+1):
            average = self.getAverageCV(num_components)
            if average > best_log_l:
                best_log_l = average
                best_num_components = num_components
        return self.base_model(best_num_components)
    def getAverageCV(self, num_components):
        log_l_fold = []
        n_splits = min(3, len(self.sequences))
        if n_splits<3:
            model = self.base_model(num_components)
            try:
                score = model.score( self.X, self.lengths ) 
            except:
                score = float("-inf")
                pass
            return score
        else:
            kf = KFold(n_splits) #default n=3
            for train_index, test_index in kf.split(self.sequences):
                #combine sequences from asl_recognizer
                X_train, lengths_train = combine_sequences( train_index, self.sequences) #go to asl_utils
                x_test, lengths_test   = combine_sequences( test_index, self.sequences )
                #build models
                model = GaussianHMM(n_components=num_components, covariance_type="diag", n_iter=1000, 
                                    random_state=self.random_state, verbose=False).fit(X_train, lengths_train)
                #score with test idx
                try:
                    curr_log_l = model.score(X_test, lengths_test) #log likelihood based on test indices
                    log_l_fold.append(curr_log_l)
                except:
                    pass
        if len(log_l_fold)>0:        
            average = sum(log_l_fold)/float(len(log_l_fold))
        elif len(log_l_fold)==0:
            average = float("-inf")
        return average
        
